export enum OrderStatus {
  WAITING_CLIENT_PAYMENT = 'WAITING_CLIENT_PAYMENT',
  WAITING_CLIENT_FINALIZATION = 'WAITING_CLIENT_FINALIZATION',
  CANCELED_BY_CLIENT = 'CANCELED_BY_CLIENT',
  IN_DELIVERY = 'IN_DELIVERY',
  CLIENT_PAID = 'CLIENT_PAID',
  CLIENT_NOT_PAID = 'CLIENT_NOT_PAID'
}
